### ISSUE TITLE
appsNamingConvention or app-naming-convention or app_naming_convention?

### ISSUE THREAD

**Issue by francopestilli** [brain-life/warehouse#118]
Which convention shall we use?

**Comment by soichih** [comment]
I like "app-naming-convention" which seems to be the most common (and often recommended) way to name github repo. But that's just my preference. I think it's good to standardize the naming convention for apps that are developed by pestillilab and hosted under brain-life org. I think it makes us look more coherent. 

However, from brain-life platform point of view, we should allow external developers to use whatever the naming convention that their lab uses - when they start registering their app on brain-life.

**Comment by soichih** [comment]
Closing this now - I believe we agreed to use app-naming-convention for our lab.
