### ISSUE TITLE
BUG> Number only subject name (like "1") breaks app submitter UI

### ISSUE THREAD

**Issue by soichih** [brain-life/warehouse#120]
If I have a datasets with just number as subject like "1", it will break the simple application submitter's dataset selecter.

**Comment by stevengeeky** [comment]
Soichi, could you describe to me exactly what breaks on the UI? Can't seem to replicate this

**Comment by stevengeeky** [comment]
@soichih

**Comment by soichih** [comment]
Steven, I tried recreating it but I couldn't. I am closing this ticket until this reoccurs. Sorry about that!
