### ISSUE TITLE
add some sort of filtering to pipeline rules based on the other available datasets for each subject

### ISSUE THREAD

**Issue by kitchell** [brain-life/warehouse#148]
It would be nice if we could add a way to filter pipeline rules based on the other available data for the subjects or based on the subjects in the current project. 

For example, I set up a pipeline rule for an app that uses only freesufer data. I wanted it to run on the freesurfer data for the HCP 3T data, but only on the freesurfer data of subjects that also have dwi data. The output was set to be archived to my private project of HCP derivatives. The was no way to specify which subjects to run on, so now I have >50 outputs archived to my project for subjects I cannot use. There is no quick way to identify these outputs either, so I will have to manually go through and delete them. 

I can see this also being an issue if future users are only interested in using a subset of subjects (say 40 HCP subjects instead of all), since they cannot just copy the freesurfer or other data over to a new project they may run into pipeline issues trying to only process some of the data. 

For the Abide2 dataset, there are many subjects with no dwi, just t1 and functional, if I want to acpc align the t1 files of just the dwi subjects, I currently cannot.

**Comment by soichih** [comment]
Yes, with our current capability, unless those datasets are tagged in a useful way, all datasets will be processed even for subjects that don't have all required dataset used by later Apps.

Would it really be an issue to go ahead and preprocess datasets even though they might not be used later on? The rule will only process subjects that have all input datasets, so as soon as such App exists within the pipeline, they should not be processed from that point on.

Are you concerned that unnecessary processing is done on some subject, or are you simply trying to keep the datasets list clean?

**Comment by kitchell** [comment]
I think i'm concerned with both, but mainly keeping the list clean. For example, I ran an app to create surfaces of freesurfer data, now I have 100 extra datasets. I am now going to run the LB spectrum app on the freesurfer surfaces, and eventually will need to download that data. 100 extra subjects may or may not make a difference when downloading that data and storing on my computer. Right now I can't easily delete or even determine which subjects also have dwi data, im only interested in those with dwi as well. I'll have to write a way to do that all the way down at the off-brainlife processing stage, which is not too difficult, but a bit annoying that it is not handled on brainlife. 

I'm not sure what the solution would be, but maybe down the line this can be solved!

**Comment by francopestilli** [comment]
@kitchell @soichih we might want to start thinking about Reduce-type of Apps. Apps that take as inputs many datasets processed on BL and reduce them into an aggregated dataset. For example `100 LB spectrum into a new DataType that aggregates across subjects what @kitchell needs.

**Comment by francopestilli** [comment]
@soichih that is an option. Also, we might need to think about some sort of *super subject*? That aggregates across subjects? At least from the perspective for the interface. I agree that the DB is great for the computation.

**Comment by kitchell** [comment]
@soichih not for the freesurfer LBspectrum unfortunately. There is no way to tag only the freesurfer LB spectrum of subjects with dwi data.

**Comment by kitchell** [comment]
yes. that is not the problem. Here is the issue:

I have 1043 subjects from HCP that have dwi data that I want to use. 

The HCP 3T data has 1103 subjects total with freesurfer data. Not all that have freesurfer have dwi. 

I ran an app that creates 3D surfaces of freesurfer data. The pipeline took all the freesurfer data from HCP and ran the app on all and saved the output for all. Now I have 1103 datasets of freesurfer surfaces. I only want 1043 datasets of freesurfer surfaces. 

If I run the LB spectrum app, I will have 1103 LB spectrum outputs tagged with freesurfer. If I go to download I will have to download all 1103 outputs. I only want to download 1043 outputs, only the outputs for those who have dwi data.

**Comment by soichih** [comment]
OK. I think I understand. I've run a mongo query to set all 3Dsurface:freesurfer datasets that has dwi data with "withdwi", and no dwi data with "nodwi". Here are the list of subjects that doesn't have dwi data.

```
"107220",
"109325",
"113417",
"114924",
"116120",
"117728",
"121315",
"121820",
"126931",
"128329",
"129432",
"129533",
"131621",
"142424",
"143527",
"145531",
"159845",
"165234",
"168038",
"169141",
"171128",
"171734",
"186949",
"190132",
"197449",
"201717",
"203721",
"207628",
"209531",
"221218",
"239136",
"355542",
"355845",
"552544",
"584355",
"611231",
"613235",
"623137",
"650746",
"662551",
"689470",
"733548",
"734247",
"745555",
"782157",
"822244",
"953764",
```

**Comment by kitchell** [comment]
Great! that should help and for now it solves my problem.  Now if that is something that the user could do, that would be helpful in the long run.

**Comment by soichih** [comment]
I wonder if we should make the "tag" a required field to prevent other users from running into the situation @kitchell ran into?

**Comment by kitchell** [comment]
I think making 'tag' required would be a good thing actually. I frequently forgot/forget to add one and I know new users will not realize how important it is until they run into a situation where they need it.

**Comment by soichih** [comment]
I've added code to automatically add a default output dataset tag (composed from the rule name). User can  remove it and replace it something else, but this should at least have *a* tag for all rule output.
