### ISSUE TITLE
Always store subject/session of a dataset as a string

### ISSUE THREAD

**Issue by stevengeeky** [brain-life/warehouse#179]
Cast on the server side if necessary (for example, if subject/session is a number, cast to a string before storing to the database)

This also means we need to run a bulk update query to fix the currently stored datasets, like this:

```javascript
#!/usr/bin/env node

const models = require('./models');
const mongoose = require('mongoose');
const config = require('./config');
const async = require('async');
models.init(function() {
    models.Datasets.find({}, (err, datasets) => {
        async.eachLimit(datasets, 10, (dataset, next) => {
            if (dataset.meta) {
                if (typeof dataset.meta.subject == 'number') {
                    dataset.meta.subject = "" + dataset.meta.subject;
                }
                if (typeof dataset.meta.session == 'number') {
                    dataset.meta.session = "" + dataset.meta.session;
                }
                dataset.markModified('meta');
                dataset.save(err => {
                    if (err) throw err;
                    else next();
                });
            }
            else {
                next();
            }
        });
    });
});
```

**Comment by soichih** [comment]
Thanks @stevengeeky I've run something siWmilar on test.brainlife.io. Can you check to see if all metadata is now normalized? I will update the API to convert subject/session/run to string.

**Comment by stevengeeky** [comment]
All datasets have been updated

**Comment by soichih** [comment]
I've run the migration script on production server, and updated warehouse API to convert subject/session/run during post/validation step for dataset schema. Please let me know if this is still an issue.
