### ISSUE TITLE
Currently the bulk submission #1

### ISSUE THREAD

**Issue by francopestilli** [brain-life/warehouse#20]
It seems that currently, bulk submission requires selecting a pair of T1/DWI for both data sets staged and selected for a process as well as for data sets staged but NOT selected for processing.

**Comment by soichih** [comment]
Franco, can you show me what you mean tomorrow?

**Comment by soichih** [comment]
@francopestilli  explained this to me, but I forgot to update this issue and now I can't remember what he meant again... @francopestilli Is this still an issue?

**Comment by francopestilli** [comment]
@soichih I think this was related to the fact that whereas the "proprocess" page automatically selects the correct data type for processing when a single subjects data only is selected, when multiple subjects are selected data types required for processing are not automatically selected for each subject independently, the user is required to manually match data type 1 subject 1 to data type 2 from subject 1 and data type 1 subject 2 to data type 2 from subject 2 etc to advance processing.

**Comment by soichih** [comment]
Ah, I see. 

You should create different process for each subject. If you mix datasets from different subjects to a single process, UI can't determine which dataset you are trying to process and user has to do more manual work. 

We need encourage user to create separate process for each subject, but I don't know what would be a good way to do that.. (maybe popup warning message?)

**Comment by francopestilli** [comment]
OK let's eliminate this issue for the moment then...

**Comment by soichih** [comment]
I don't think we should close this.. because I've seen people running into a similar situation - although they eventually figure out and start creating separate processes to process different subject. We should definitely include some information on the tutorial
