### ISSUE TITLE
Add button to select all dataset in project

### ISSUE THREAD

**Issue by skoudoro** [brain-life/warehouse#203]
Hi Brain-Life Team,

In my project, after filtering the dataset, I would like to select/unselect them all with one button instead of select 100 checkboxes. 

Is it possible to add this button?

Thanks!

**Comment by stevengeeky** [comment]
skoudoro, you can hold `shift` while clicking a second checkbox to select/unselect all of the checkboxes in between

**Comment by skoudoro** [comment]
oh, nice, good to know!

Thanks @stevengeeky!

closing
