### ISSUE TITLE
Publication record can contain *versions*

### ISSUE THREAD

**Issue by soichih** [brain-life/warehouse#209]
We probably need to rerun / republish most of the O3D published datasets (input dwi was flipped, and we need to add wmc:pre_life to the publication). We could allow publications to have multiple *versions* of output datasets by letting user to re-publish currently archived datasets. 

So, to *fix* the O3D issue, we could..

1) remove all affected datasets from O3D archive.
2) rerun pipelines.
3) Go to the existing publication record, and re-publish datasets under a new "version" tag.

**Comment by francopestilli** [comment]
Yes, this will be defintiely helpful.
