### ISSUE TITLE
Allow scrolling of app description on task submission/process page or add a way to show possible input options

### ISSUE THREAD

**Issue by kitchell** [brain-life/warehouse#75]
Currently, when submitting a new task on the process page the description of the app is cut off. This is a problem when the app description describes the possible options you can use as inputs for the app. For example, the Laplace beltrami app has a string input labeled 'normalization'. The user can input four possible strings: none, 'index', 'area' or 'areaindex', but the only way the user knows what options they can input is by reading the app description. 

I think we should add the capability to scroll the app description when submitting a new task. I also think it would be helpful if we could list next to the input boxes what the possible options are.

**Comment by soichih** [comment]
Yes, we should display the full description of the app while submitting the task.

Although.. it sounds like we should add a new input type of "enum" where we let user select from possible values.

In the app input config, it could look like this.

```
"normalization": {
    "type": "enum",
    "default": "areaindex",
    "values": [
     {
        "value": "none", 
        "label": "None", 
        "desc": "Don't perform any normalization"
    },
     {
        "value": "area", 
        "label": "2D Area", 
        "desc": "Uses the area of the 2D structure as in Reuter et al. 2006."
    },
    {
        "value": "index", 
        "label": "Eigenvalue Index", 
        "desc": "Divide the eigenvalues by their index to account for linear increase of Eigenvalue magnitude (Weyl's law in 2D) as suggested in Reuter et al. (2006) "
    },
    {
        "value": "areaindex", 
        "label": "Area Index",
        "desc": "divide the eigenvalues by their index to account for linear increase of Eigenvalue magnitude (Weyl's law in 2D) as suggested in Reuter et al. (2006) "
    }
    ]
}
```

**Comment by kitchell** [comment]
yes, I like the enum input type!

**Comment by soichih** [comment]
@kitchell 

I've released an update to allow you to use enum input type.

You can replace your "normalization" configuration with the one that I've posted yesterday.

**Comment by kitchell** [comment]
perfect! thank you.
