### ISSUE TITLE
Images viewer needs to adjust depending on number of images to display

### ISSUE THREAD

**Issue by kitchell** [brain-life/warehouse#85]
the life and AFQ quality check app is now set up to use the images data type, but when I view the output with the images viewer it puts the image in the upper left corner and it is very small. We need to have the viewer adjust to display the image correctly.

**Comment by soichih** [comment]
We will update the images viewer to override the number of default colums to be the number of input images if it's less than 4. @stevengeeky Would you like to work on this?

Note to myself.. We could add properties to images.json to specify the number of columns.. but that would blur the line between data producer and visualizer, and I think it's a bad approach.

**Comment by stevengeeky** [comment]
@soichih I can work on this, in addition to the application configuration editor thingy

**Comment by soichih** [comment]
I just noticed that we haven't updated this yet. I will work on this.
